import os
from dotenv import load_dotenv

load_dotenv()

class Config:
    # --- Exchange Settings ---
    # We will use cryptocom for live and binance for backtesting data
    EXCHANGE_ID = 'cryptocom'
    API_KEY = os.getenv('API_KEY', '')
    API_SECRET = os.getenv('API_SECRET', '')

    # --- Telegram Settings ---
    TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '')
    TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID', '')

    # --- AI Settings ---
    # The URL generated by ngrok from the Colab instance.
    AI_API_URL = os.getenv('AI_API_URL', None)

    # --- Trading Parameters ---
    BASE_CAPITAL = 150.0  # USDT
    MAX_ACTIVE_TRADES = 4 # Allow up to 4 concurrent trades to fully utilize 150 USDT (4 * 35 = 140)

    # Target symbols for multi-asset scanning (Spot)
    SYMBOLS = ['BTC/USDT', 'ETH/USDT', 'SOL/USDT', 'DOGE/USDT', 'XRP/USDT']

    # Capital allocation per tier (USDT) - Micro DCA
    TIER_1_AMOUNT = 5.0
    TIER_2_AMOUNT = 10.0
    TIER_3_AMOUNT = 20.0

    # Trigger conditions (price drop % from average entry price)
    TIER_2_DROP_PCT = -0.015  # -1.5%
    TIER_3_DROP_PCT = -0.030  # -3.0%

    # Take Profit & Stop Loss
    TP_NET_PROFIT = 0.3      # USDT (Fast turnover)
    SL_MAX_LOSS = -5.0       # USDT per position

    # Exchange Fee Estimation (Maker/Taker roughly 0.075% for default tier, we use 0.1% to be safe)
    FEE_RATE = 0.001

    # Timeframes - Shorter timeframe for higher frequency
    TIMEFRAME = '5m'

config = Config()
