import pandas as pd
import pandas_ta as ta

class SignalEngine:
    def __init__(self):
        pass

    def calculate_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculates required technical indicators using pandas-ta.
        Adds RSI and Bollinger Bands to the dataframe.
        """
        if df.empty or len(df) < 20:
            return df

        # Calculate 15m RSI
        df.ta.rsi(length=14, append=True)

        # Calculate Bollinger Bands (20, 2)
        df.ta.bbands(length=20, std=2, append=True)

        return df

    def check_tier_1_signal(self, df: pd.DataFrame) -> bool:
        """
        Checks if conditions for Tier 1 entry are met.
        Condition: 15m RSI < 30 OR Price touches/crosses lower Bollinger Band.
        """
        if df.empty or len(df) < 20:
            return False

        latest = df.iloc[-1]

        # Column names generated by pandas-ta usually look like RSI_14, BBL_20_2.0
        rsi_col = [c for c in df.columns if c.startswith('RSI_')]
        bbl_col = [c for c in df.columns if c.startswith('BBL_')]

        if not rsi_col or not bbl_col:
            return False

        rsi_val = latest[rsi_col[0]]
        bbl_val = latest[bbl_col[0]]
        close_val = latest['close']

        if pd.isna(rsi_val) or pd.isna(bbl_val):
            return False

        if rsi_val < 30 or close_val <= bbl_val:
            return True

        return False

    def check_tier_2_signal(self, current_price: float, avg_entry_price: float, drop_pct: float, df: pd.DataFrame) -> bool:
        """
        Checks if conditions for Tier 2 entry are met.
        Condition: Price drops by TIER_2_DROP_PCT AND momentum indicates potential support.
        For simplicity in momentum, we check if RSI is showing oversold or turning up.
        """
        if current_price > avg_entry_price * (1 + drop_pct):
            return False

        if df.empty or len(df) < 2:
            return False

        rsi_col = [c for c in df.columns if c.startswith('RSI_')]
        if not rsi_col:
            return False

        latest_rsi = df.iloc[-1][rsi_col[0]]
        prev_rsi = df.iloc[-2][rsi_col[0]]

        # Basic momentum check: RSI is oversold or starting to turn up
        if latest_rsi < 35 or latest_rsi > prev_rsi:
            return True

        return False

    def check_tier_3_signal(self, current_price: float, avg_entry_price: float, drop_pct: float) -> bool:
        """
        Checks if conditions for Tier 3 entry are met.
        Condition: Price continues to drop reaching extreme level (TIER_3_DROP_PCT).
        """
        if current_price <= avg_entry_price * (1 + drop_pct):
            return True
        return False

    def evaluate_cooldown(self, df: pd.DataFrame) -> bool:
        """
        Evaluates if the market has stabilized after a Stop Loss.
        Returns True if the cooldown period can end (market looks stable).
        Condition: We might look for RSI > 40 and closing above moving average.
        """
        if df.empty or len(df) < 20:
            return False

        latest = df.iloc[-1]

        rsi_col = [c for c in df.columns if c.startswith('RSI_')]
        if not rsi_col:
            return False

        rsi_val = latest[rsi_col[0]]
        close_val = latest['close']

        # Calculate a simple moving average for trend check
        sma_20 = df['close'].rolling(window=20).mean().iloc[-1]

        if pd.isna(rsi_val) or pd.isna(sma_20):
            return False

        if rsi_val > 40 and close_val > sma_20:
            return True

        return False
