import pandas as pd
import pandas_ta as ta
import requests
import logging
from src.config import config

logger = logging.getLogger(__name__)

class SignalEngine:
    def __init__(self):
        self.ai_url = config.AI_API_URL

    def get_ai_prediction(self, symbol: str, df: pd.DataFrame) -> float:
        """
        Sends historical data to the Colab AI API to get the predicted next close price.
        Returns the predicted close price. If it fails, returns None.
        """
        if not self.ai_url:
            return None

        try:
            # We send the last 400 candles to the AI
            lookback_df = df.tail(400).copy()
            # Ensure 'timestamp' column is correctly formatted as string
            lookback_df['timestamp'] = lookback_df['timestamp'].dt.strftime('%Y-%m-%d %H:%M:%S')

            payload = {
                "symbol": symbol,
                "lookback_data": lookback_df[['timestamp', 'open', 'high', 'low', 'close', 'volume']].to_dict('records'),
                "pred_len": 1
            }

            url = f"{self.ai_url}/predict"
            response = requests.post(url, json=payload, timeout=10)
            response.raise_for_status()

            data = response.json()
            predicted_close = data.get("predicted_close")
            logger.info(f"AI Prediction for {symbol}: {predicted_close}")
            return predicted_close
        except Exception as e:
            logger.error(f"Failed to fetch AI prediction (fallback to traditional): {e}")
            return None

    def calculate_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculates required technical indicators using pandas-ta.
        Adds RSI and Bollinger Bands to the dataframe.
        """
        if df.empty or len(df) < 20:
            return df

        # Calculate 15m RSI
        df.ta.rsi(length=14, append=True)

        # Calculate Bollinger Bands (20, 2)
        df.ta.bbands(length=20, std=2, append=True)

        return df

    def check_tier_1_signal(self, symbol: str, df: pd.DataFrame) -> bool:
        """
        Checks if conditions for Tier 1 entry are met.
        Condition: 15m RSI < 30 OR Price touches/crosses lower Bollinger Band.
        AI Enhancement: If the AI is configured, it will require the predicted close price to be higher than the current close.
        """
        if df.empty or len(df) < 20:
            return False

        latest = df.iloc[-1]

        # Column names generated by pandas-ta usually look like RSI_14, BBL_20_2.0
        rsi_col = [c for c in df.columns if c.startswith('RSI_')]
        bbl_col = [c for c in df.columns if c.startswith('BBL_')]

        if not rsi_col or not bbl_col:
            return False

        rsi_val = latest[rsi_col[0]]
        bbl_val = latest[bbl_col[0]]
        close_val = latest['close']

        if pd.isna(rsi_val) or pd.isna(bbl_val):
            return False

        traditional_signal = (rsi_val < 30 or close_val <= bbl_val)

        if not traditional_signal:
            return False

        # Traditional signal triggered. Now query AI to act as a filter if available.
        predicted_close = self.get_ai_prediction(symbol, df)
        if predicted_close is not None:
            # AI is active. Only buy if the AI predicts the price will go up.
            if predicted_close > close_val:
                logger.info(f"Tier 1 AI confirmation passed: Predicted {predicted_close} > Current {close_val}")
                return True
            else:
                logger.info(f"Tier 1 AI confirmation failed: Predicted {predicted_close} <= Current {close_val}. Skipping trade.")
                return False

        # If AI is not active or failed, trust the traditional signal.
        return True

    def check_tier_2_signal(self, current_price: float, avg_entry_price: float, drop_pct: float, df: pd.DataFrame) -> bool:
        """
        Checks if conditions for Tier 2 entry are met.
        Condition: Price drops by TIER_2_DROP_PCT AND momentum indicates potential support.
        For simplicity in momentum, we check if RSI is showing oversold or turning up.
        """
        if current_price > avg_entry_price * (1 + drop_pct):
            return False

        if df.empty or len(df) < 2:
            return False

        rsi_col = [c for c in df.columns if c.startswith('RSI_')]
        if not rsi_col:
            return False

        latest_rsi = df.iloc[-1][rsi_col[0]]
        prev_rsi = df.iloc[-2][rsi_col[0]]

        # Basic momentum check: RSI is oversold or starting to turn up
        if latest_rsi < 35 or latest_rsi > prev_rsi:
            return True

        return False

    def check_tier_3_signal(self, current_price: float, avg_entry_price: float, drop_pct: float) -> bool:
        """
        Checks if conditions for Tier 3 entry are met.
        Condition: Price continues to drop reaching extreme level (TIER_3_DROP_PCT).
        """
        if current_price <= avg_entry_price * (1 + drop_pct):
            return True
        return False

    def evaluate_cooldown(self, df: pd.DataFrame) -> bool:
        """
        Evaluates if the market has stabilized after a Stop Loss.
        Returns True if the cooldown period can end (market looks stable).
        Condition: We might look for RSI > 40 and closing above moving average.
        """
        if df.empty or len(df) < 20:
            return False

        latest = df.iloc[-1]

        rsi_col = [c for c in df.columns if c.startswith('RSI_')]
        if not rsi_col:
            return False

        rsi_val = latest[rsi_col[0]]
        close_val = latest['close']

        # Calculate a simple moving average for trend check
        sma_20 = df['close'].rolling(window=20).mean().iloc[-1]

        if pd.isna(rsi_val) or pd.isna(sma_20):
            return False

        if rsi_val > 40 and close_val > sma_20:
            return True

        return False
